security:
    encoders:
        Hollo\TrackerBundle\Entity\User: plaintext

    providers:
        our_db_provider:
            entity:
                class: HolloTrackerBundle:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/fraction, roles: ROLE_USER }
        - { path: ^/position, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
