<?php

namespace Hollo\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends EntityRepository
{
    public function getRecent(User $entity)
    {
        $date = new \DateTime();
        $date->modify('-1 day');

        return $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->andWhere('p.createdAt > :date')
            ->orderBy('p.id', 'ASC')
            ->setParameter('user', $entity)
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult()
            ;
    }

    public function getRange(User $user, \DateTime $start, \DateTime $end)
    {
        return $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->andWhere('p.createdAt > :start')
            ->andWhere('p.createdAt < :end')
            ->setParameter('user', $user)
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->getQuery()
            ->getResult()
            ;
    }
}
