<?php

namespace Hollo\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoutOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutOutRepository extends EntityRepository
{
    public function getLatest(User $entity)
    {
        return $this->createQueryBuilder('s')
            ->where('s.user = :user')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('user', $entity)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function getRecent($limit=20)
    {
        $date = new \DateTime();
        $date->modify('-5 days');

        return $this->createQueryBuilder('s')
            ->where('s.createdAt > :date')
            ->setParameter('date', $date)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
            ;
    }
}
