<?php

namespace Hollo\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoutOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutOutRepository extends EntityRepository
{
    public function getLatest(User $entity)
    {
        return $this->createQueryBuilder('s')
            ->where('s.user = :user')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('user', $entity)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
