<?php

namespace Hollo\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoutOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutOutRepository extends EntityRepository
{
}
